/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockUnknow: typeof import('./components/block/block-unknow.vue')['default']
    CardHead: typeof import('./components/common/card-head.vue')['default']
    ColumnOne: typeof import('./components/block/column-one.vue')['default']
    FixedBtn: typeof import('./components/common/fixed-btn.vue')['default']
    GoodsItem: typeof import('./components/business/goods-item.vue')['default']
    GradientTitle: typeof import('./components/common/gradient-title.vue')['default']
    Map: typeof import('./components/common/map.vue')['default']
    RecommendProducts: typeof import('./components/business/recommend-products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanNavBar: typeof import('vant/es')['NavBar']
    YsTabbar: typeof import('./components/common/ys-tabbar.vue')['default']
  }
}
