export const platformMap = {
  FLZ: 'FLZ',
  AMALL: 'AMALL',
  AMALLDECRYPT: 'AMALLDECRYPT',
  APLUS: 'APLUS',
  CY: 'CY',
  COMMON: 'COMMON',
  UNION: 'UNION',
  APLUSDECRYPT: 'APLUSDECRYPT',
  AMALLFLZDECRYPT: 'AMALLFLZDECRYPT',
  DECRYPT: 'DECRYPT'
} as const
